config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :shops
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :shop

  # Check close status, if checked validation pass,
  # not matter open_at or close_at fields status.
  # If not, check that open_at < close_at
  validate :simple_opening_hour

  # Check multiple_slots status, if checked verification that open_at_ms < close_at_ms
  validate :multiple_opening_hour

  # Verification that multiple slots opening hours don't overlap
  validate :multiple_opening_hour_overlap

  private

  def simple_opening_hour
    return if closed

    if close_at <= open_at
      errors.add(:close_at, "Closing time cannot be before the opening time")
    end
  end

  def multiple_opening_hour
    return unless multiple_slots

    if close_at_ms <= open_at_ms
      errors.add(:close_at_ms, "Closing time cannot be before the opening time")
    end
  end

  def multiple_opening_hour_overlap
    return unless multiple_slots

    if open_at_ms <= close_at
      errors.add(:open_at_ms, "Opening slots cannot overlap")
    end
  end
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :schedules, dependent: :destroy

  # Use of nested attributes to allows to save shop schedules attributes
  # through its associated parent (shop)
  accepts_nested_attributes_for :schedules

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[show edit update destroy]

  def index
    @shops = Shop.all
  end

  def show
    @schedules_array = []
    # we save all schedules attributes of a shop in schedules_array
    # to manipulate it in the view
    @shop.schedules.each do |sh|
      @schedules_array << sh
    end
  end

  def new
    @shop = Shop.new
    # Using this way (instead of an iteration directly in the view),
    # we correct the new form duplication in Shop new when validation error
    7.times { @shop.schedules.build }
  end

  def create
    @shop = Shop.new(shops_params)
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @shop.update(shops_params)
    redirect_to shop_path(@shop)
  end

  def destroy
    @shop.destroy
    redirect_to(shops_path)
  end

  private

  def shops_params
    params.require(:shop).permit(:name, schedules_attributes: %i[id open_at close_at weekday closed multiple_slots open_at_ms close_at_ms])
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedule_helper.rb
module ScheduleHelper
  def jours
    {
      lundi: 0,
      mardi: 1,
      mercredi: 2,
      jeudi: 3,
      vendredi: 4,
      samedi: 5,
      dimanche: 6
    }
  end

  def days
    {
      monday: 0,
      tuesday: 1,
      wednesday: 2,
      thursday: 3,
      friday: 4,
      saturday: 5,
      sunday: 6
    }
  end

  # today method will return the current weekday
  def today
    Time.now.strftime("%A").downcase
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopOpeningHours</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="wrapper">
      <%= yield %>
    </div>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/home_banner"%>

<div class = "mt-5 text-center">
  <%= link_to "Liste des magasins", shops_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_footer.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/FabrizioDurand" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/fabrizio-durand-19264b97" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <h2>ShopSchedule</h2>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-heart"></i>
  </div>
</div>

app/views/shared/_home_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://img.freepik.com/vecteurs-libre/paysage-rue-urbaine-petite-boutique-restaurant_107791-1008.jpg?t=st=1675243851~exp=1675244451~hmac=00f4b454e9d530b8010f374a5e2292bebf9177b9d59e7e370c12bf930a3b4710);">
  <div class="container">
    <h1>Trouvez les horaires de votre magasin préféré!</h1>
    <h3>Parcourez les horaires des magasins du monde entier</h3>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://img.freepik.com/vecteurs-libre/fond-facade-hotel-plat_23-2148157379.jpg?w=826&t=st=1671727611~exp=1671728211~hmac=750a63d8e6e67facabb8cf95fe6166d60fc8f1017606bd4b697ebc093bfff148" %>
    <% end %>
    <h2>ShopSchedule</h2>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Liste des magasins", shops_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/shops/_edit_form.html.erb
<%= simple_form_for(shop) do |f| %>
    <%= f.input :name, label: "Nom du magasin" %>
    <%# we had a counter "count" to associate the right weekday directly%>
    <% count = 0 %>
      <%= f.simple_fields_for :schedules do |schedule| %>
        <div class="my-5">
          <div class="d-flex justify-content-center">
            <%= schedule.input :weekday, label: false, input_html: { value: jours.key(count), readonly: "readonly" } %>
          </div>
          <div class="d-flex justify-content-center mx-3">
            <div data-action="click->schedule-manager#checkIfClosed">
              <%= schedule.input :closed, label: "Jour de fermeture", input_html: { data: { target: "schedule-manager.closedDay" } } %>
            </div>
            <div data-schedule-manager-target="openingHours" class="d-flex justify-content-center mx-5">
              <%= schedule.input :open_at, label: "Heure d'ouverture", minute_step: 15, include_blank: true, input_html: { data: { target: "schedule-manager.open" } } %>
              <%= schedule.input :close_at, label: "Heure de fermeture", minute_step: 15, include_blank: true, input_html: { data: { target: "schedule-manager.close" } }%>
            </div>
          </div>

          <div class="d-flex justify-content-center mx-3">
            <div data-action="click->schedule-manager#checkIfMultipleSlots" data-schedule-manager-target="multipleSlotsCheck">
              <%= schedule.input :multiple_slots, label: "Plusieurs créneaux d'ouverture", input_html: { data: { target: "schedule-manager.multipleSlots" } }  %>
            </div>
            <div data-schedule-manager-target="openingHourMs" class="d-none d-flex justify-content-center mx-5">
              <%= schedule.input :open_at_ms, label: "Heure d'ouverture", minute_step: 15, include_blank: true %>
              <%= schedule.input :close_at_ms, label: "Heure de fermeture", minute_step: 15, include_blank: true %>
            </div>
          </div>
        </div>
        <% count += 1 %>
      <% end %>
    <div class="mb-5 text-center">
      <%= f.submit "Editer le magasin", class:"btn btn-primary"%>
    </div>
  <% end %>

app/views/shops/_new_form.html.erb
<%= simple_form_for(shop) do |f| %>
    <%= f.input :name, label: "Nom du magasin" %>
    <%# we use "count" as a counter to associate the right weekday directly%>
    <% count = 0 %>
      <%= f.simple_fields_for :schedules do |schedule| %>
        <div class="my-5">
          <div class="d-flex justify-content-center">
          <%# we display the weekdays as readonly %>
            <%= schedule.input :weekday, label: false, input_html: { value: jours.key(count), readonly: "readonly" } %>
          </div>
          <div class="d-flex justify-content-center mx-3">
            <div data-action="click->schedule-manager#checkIfClosed">
              <%= schedule.input :closed, label: "Jour de fermeture", input_html: { data: { target: "schedule-manager.closedDay" } } %>
            </div>
            <div data-schedule-manager-target="openingHours" class="d-flex justify-content-center mx-5">
            <%# time fields are set to display minutes only by 15minutes slots %>
              <%= schedule.input :open_at, label: "Heure d'ouverture", minute_step: 15, include_blank: true, input_html: { data: { target: "schedule-manager.open" } } %>
              <%= schedule.input :close_at, label: "Heure de fermeture", minute_step: 15, include_blank: true, input_html: { data: { target: "schedule-manager.close" } }%>
            </div>
          </div>

          <div class="d-flex justify-content-center mx-3">
            <div data-action="click->schedule-manager#checkIfMultipleSlots" data-schedule-manager-target="multipleSlotsCheck">
              <%= schedule.input :multiple_slots, label: "Plusieurs créneaux d'ouverture", input_html: { data: { target: "schedule-manager.multipleSlots" } }  %>
            </div>
            <div data-schedule-manager-target="openingHourMs" class="d-none d-flex justify-content-center mx-5">
              <%= schedule.input :open_at_ms, label: "Heure d'ouverture", minute_step: 15, include_blank: true %>
              <%= schedule.input :close_at_ms, label: "Heure de fermeture", minute_step: 15, include_blank: true %>
            </div>
          </div>
        </div>
        <% count += 1 %>
      <% end %>
    <div class="mb-5 text-center">
      <%= f.submit "Créer le magasin", class:"btn btn-primary"%>
    </div>
  <% end %>

app/views/shops/edit.html.erb
<div class="container mt-3" data-controller = "schedule-manager">
  <h1>Editer magasin</h1>
    <%# rendering of edit_form %>
  <%= render "edit_form", shop: @shop %>
</div>

app/views/shops/index.html.erb
<div class="container mt-3">
  <div class=" d-flex justify-content-center">
    <div>
      <h1>Liste des magasins</h1>
      <% if @shops.empty? %>
        <h3>Pas de magasins disponible, ajoutez-en un!</h3>
      <% end %>
      <% @shops.each do |shop| %>
        <ul>
          <li><%= link_to shop.name, shop_path(shop)%></li>
        </ul>
      <% end %>
    </div>
  </div>
  <div class="mt-3 d-flex justify-content-center">
    <%= link_to "Ajouter un nouveau magasin", new_shop_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/shops/new.html.erb
<div class="container mt-3" data-controller = "schedule-manager">
  <h1>Ajouter un magasin</h1>
  <%# rendering of new_form %>
  <%= render "new_form", shop: @shop %>
</div>

app/views/shops/show.html.erb
<div class="container mt-3">
  <div class=" d-flex justify-content-center">
    <div>
      <h1><%= @shop.name%></h1>
      <table>
        <%# we modify schedules_array to reorder the days depending on the current day (we put current day in first) %>
        <%# days and today are helpers %>
        <% @schedules_array.rotate(days[today.to_sym]).each_with_index do |sh, i|%>
          <tr>
          <%# if i ==0 then today the current weekday and we display the shop information in bold%>
            <% if i == 0 %>
              <% if sh.closed %>
                <th>Horaires : </th>
                <th><%= sh.weekday%></th>
                <th> Fermé </th>
              <% elsif sh.multiple_slots %>
                <th>Horaires : </th>
                <th><%= sh.weekday%></th>
                <%# time fields are modified to only display hours:minutes %>
                <th> <%= sh.open_at.strftime("%k:%M") %>-<%= sh.close_at.strftime("%k:%M") %>, <%= sh.open_at_ms.strftime("%k:%M") %>-<%= sh.close_at_ms.strftime("%k:%M") %></th>
              <% else %>
                <th>Horaires : </th>
                <th><%= sh.weekday%></th>
                <th> <%= sh.open_at.strftime("%k:%M") %>-<%= sh.close_at.strftime("%k:%M") %></th>
              <% end %>
            <% else %>
              <% if sh.closed %>
                <td></td>
                <td><%= sh.weekday%></td>
                <td> Fermé </td>
              <% elsif sh.multiple_slots %>
                <td></td>
                <td><%= sh.weekday%></td>
                <td> <%= sh.open_at.strftime("%k:%M") %>-<%= sh.close_at.strftime("%k:%M") %>, <%= sh.open_at_ms.strftime("%k:%M") %>-<%= sh.close_at_ms.strftime("%k:%M") %> </td>
              <% else %>
                <td></td>
                <td><%= sh.weekday%></td>
                <td> <%= sh.open_at.strftime("%k:%M") %>-<%= sh.close_at.strftime("%k:%M") %> </td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="mt-5 d-flex justify-content-center">
    <%= link_to "Editer", edit_shop_path(@shop), class: "btn btn-primary btn-sm  mx-3" %>
    <%= link_to "Supprimer", shop_path(@shop), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},class: "btn btn-danger btn-sm  mx-3" %>
  </div>
    <div class="mt-5 d-flex justify-content-center">
      <%= link_to "Liste des magasins", shops_path, class: "btn btn-primary  mx-3" %>
  </div>
</div>